# Site settings
title: WellVersedHub
email: zipho.m@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "wellversedhub.com" # the base hostname & protocol for your site

twitter_username: ziphozakhemashologu
github_username: zipho.m

# Build settings
markdown: kramdown
